downsampleParams:
  isPassthroughdownsample: false
  passthroughAxis: x
  passthroughMin: -1.0
  passthroughMax: 1.0
  isRandomdownsample: true
  isVoxeldownSample: false
  isUniformdownsample: false
  leafSize: 0.2

plyFilePath: ../ply/1744870787.176924.ply
